[package]
name = "bevy_snake"
version = "0.7.0"
authors = ["Marcus Buffett <marcusbuffett@me.com>", "Alan Klas <alanklas@me.com"]
edition = "2021"

[dependencies]
bevy = "0.9"
rand = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3